(
 (:id 1   :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Alamire primo grave" :root :a :ordine 1 :flag :diplomatic :comment "")
 (:id 2   :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "terza minore" :departure 1 :destination 3 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 3   :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Gsolreut secondo" :root :g :ordine 2 :flag :diplomatic :comment "")
 (:id 4   :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "[terza] maggiore" :departure 1 :destination 5 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 5   :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Ffaut naturale diatonico, cioè nel primo ordine" :root :f :ordine 1 :flag :diplomatic :comment "")
 (:id 6   :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "quinta" :departure 1 :destination 8 :direction :down :group :quinta :flag :diplomatic :comment "")
 (:id 7   :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "sopradetto Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« wird impliziert.")
 (:id 8   :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Dsolre" :root :d :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 9   :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "sesta minore" :departure 1 :destination 10 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 10  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Dsolre secondo" :root :d :ordine 2 :flag :diplomatic :comment "")
 (:id 11  :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "sesta maggiore" :departure 1 :destination 12 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 12  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Cfaut primo" :root :c :ordine 1 :flag :diplomatic :comment "")
 (:id 13  :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "ottava" :departure 1 :destination 14 :direction :down :group :ottava :flag :diplomatic :comment "")
 (:id 14  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Are" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 15  :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "terza minore" :departure 16 :destination 17 :direction :down :group :terza :flag :diplomatic :comment "Dieses Intervall wird folgendermassen präzisiert: »quella [terza] minore che noi usiamo«.")
 (:id 16  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Alamire primo grave" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 17  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Gsolreut secondo" :root :g :ordine 2 :flag :diplomatic :comment "")
 (:id 18  :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "[terza minore] propinqua" :departure 16 :destination 19 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 19  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Gsolreut terzo" :root :g :ordine 3 :flag :diplomatic :comment "")
 (:id 19  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Ffaut terzo in quarto ordine" :root :f :ordine 4 :flag :anti-septimal :comment "Das soll in Ffaut terzo in quarto ordine korrigiert werden, denn es handelt sich dabei um die /terza minore propinqua/ unterhalb A. Gsolreut terzo [G♭] wäre die /terza manco di minore/ oder /terza minima/, was nicht in die Reihe der Konsonanzen in den folgenden Kapiteln passt und auch nicht mit dem Notenbeispiel übereinstimmt. Diese septimale Mollterz ist jedoch ein sehr interessanter Klang. Es ist zu diskutieren, warum Vicentino etwas später genau diese Terz (A-Ḟ) noch einmal explizit nennt. Dies könnte ein Hinweis darauf sein, dass er an dieser Stelle eben doch die septimale Terz (A-G♭) meint.")
 (:id 20  :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "propinqua della terza minore" :departure 21 :destination 22 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 21  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 22  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Ffaut terzo in quarto ordine" :root :f :ordine 4 :flag :diplomatic :comment "")
 (:id 23  :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "propinqua della terza maggiore" :departure 24 :destination 25 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 24  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 25  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Ffaut secondo in terzo ordine" :root :f :ordine 3 :flag :diplomatic :comment "")
 (:id 26  :category :interval :libro 5 :chapter 8 :folio (106 . :recto) :original-name "quinta" :departure 24 :destination 27 :direction :down :group :quinta :flag :diplomatic :comment "")
 (:id 27  :category :key      :libro 5 :chapter 8 :folio (106 . :recto) :original-name "Dsolre" :root :d :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 28  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "sesta minore" :departure 29 :destination 30 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 29  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 30  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Dsolre secondo" :root :d :ordine 2 :flag :diplomatic :comment "")
 (:id 31  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "[sesta minore] propinqua" :departure 29 :destination 32 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 32  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut terzo in quarto ordine" :root :c :ordine 4 :flag :diplomatic :comment "")
 (:id 33  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "sesta maggiore" :departure 29 :destination 34 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 34  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut primo" :root :c :ordine 1 :flag :diplomatic :comment "")
 (:id 35  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut terzo in quarto ordine" :root :c :ordine 4 :flag :diplomatic :comment "")
 (:id 35  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut primo" :root :c :ordine 1 :flag :obvious :comment "Sollte in /Cfaut primo/ korrigiert werden, da es als /Cfaut terzo in quarto ordine/ eine unübliche Referenz auf ein /propinqua/-Intervall darstellt. Korrektur ist nachdrücklich empfohlen, denn hier wird von der /propinqua/ einer Taste gesprochen, was die Klärung in den folgenden Zeilen auslöst, in der die unregelmässige Abfolge von Tasten innerhalb der /semitoni naturali/ erklärt wird.")
 (:id 36  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "sesta maggiore propinqua" :departure 37 :destination 38 :direction :down :group :sesta :flag :diplomatic :comment "»questa propinqua sara dura, perche va verso la settima,et si salvera con la sua sesta«.")
 (:id 37  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 38  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut secondo in terzo ordine" :root :c :ordine 3 :flag :diplomatic :comment "")
 (:id 39  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut" :root :c :ordine 1 :flag :diplomatic :comment "Generisch zu verstehen.")
 (:id 40  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Bmi" :root :b :ordine 1 :flag :diplomatic :comment "Generisch zu verstehen.")
 (:id 41  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "secondo Cfaut nel terzo ordine" :root :c :ordine 3 :flag :diplomatic :comment "")
 (:id 42  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "terzo Cfaut in quarto ordine" :root :c :ordine 4 :flag :diplomatic :comment "")
 (:id 42  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Bmi quarto" :root :b :ordine 4 :flag :in-discussion :comment "Luigi schlägt diese Lesart vor.")
 (:id 43  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut secondo nel terzo ordine" :root :c :ordine 3 :flag :diplomatic :comment "")
 (:id 44  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut terzo" :root :c :ordine 3 :flag :diplomatic :comment "Hier als B♯ verstanden, demonstriert die Versuchung, diese Taste /terzo/ zu nennen, weil sie im /terzo ordine/ liegt, was aber falsch ist, denn sie ist die erste Taste nach dem Cfaut, also das /Cfaut secondo/ (/nel terzo ordine/).")
 (:id 45  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "primo Cfaut" :root :c :ordine 1 :flag :diplomatic :comment "")
 (:id 46  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Cfaut secondo [in terzo ordine]" :root :c :ordine 3 :flag :diplomatic :comment "Verkürzung von /Cfaut secondo in terzo ordine/, wird im Text erkläutert.")
 (:id 47  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "terzo Cfaut posto nel quarto ordine" :root :c :ordine 4 :flag :diplomatic :comment "Hier sieht Luigit Diskussionsbedarf.")
 (:id 48  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 49  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 50  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 51  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 52  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 53  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Gsolreut" :root :g :ordine 1 :flag :diplomatic :comment "Generisch zu verstehen.")
 (:id 54  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Ffaut" :root :f :ordine 1 :flag :diplomatic :comment "Generisch zu verstehen.")
 (:id 55  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "terza minore" :departure 56 :destination 57 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 56  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "")
 (:id 57  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Csolfaut primo" :root :c :ordine 1 :flag :diplomatic :comment "")
 (:id 58  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "[terza minore] propinqua" :departure 56 :destination 59 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 59  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Csolfaut terzo in quarto ordine" :root :c :ordine 4 :flag :diplomatic :comment "")
 (:id 60  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "terza maggiore" :departure 56 :destination 61 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 61  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Dlasolre secondo" :root :d :ordine 2 :flag :diplomatic :comment "")
 (:id 62  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "[terza maggiore] propinqua" :departure 56 :destination 63 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 63  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Dlasolre terzo" :root :d :ordine 3 :flag :diplomatic :comment "")
 (:id 64  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "quinta" :departure 65 :destination 66 :direction :up :group :quinta :flag :diplomatic :comment "")
 (:id 65  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 66  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Elami" :root :e :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 67  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "semitono maggiore" :departure 66 :destination 69 :direction :up :group :semitono :flag :diplomatic :comment "")
 (:id 68  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "sesta minore" :departure 65 :destination 69 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 69  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Ffaut acuto primo" :root :f :ordine 1 :flag :diplomatic :comment "")
 (:id 70  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "diesis enarmonico" :departure 69 :destination 72 :direction :up :group :diesis :flag :diplomatic :comment "")
 (:id 71  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "[sesta minore] propinqua" :departure 65 :destination 72 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 72  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Ffaut terzo, nel quarto ordine" :root :f :ordine 4 :flag :diplomatic :comment "")
 (:id 73  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "sesta maggiore" :departure 74 :destination 75 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 74  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 75  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Gsolreut acuto secondo" :root :g :ordine 2 :flag :diplomatic :comment "")
 (:id 76  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "[sesta maggiore] propinqua" :departure 74 :destination 77 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 77  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Gsolreut acuto secondo" :root :g :ordine 2 :flag :diplomatic :comment "")
 (:id 78  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Gsolreut quinto" :root :g :ordine 5 :flag :diplomatic :comment "")
 (:id 79  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "il terzo [Gsolreut]" :root :g :ordine 3 :flag :diplomatic :comment "")
 (:id 80  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "comma" :departure 77 :destination 78 :direction :up :group :comma :flag :diplomatic :comment "")
 (:id 81  :category :interval :libro 5 :chapter 8 :folio (106 . :verso) :original-name "ottava" :departure 82 :destination 83 :direction :up :group :ottava :flag :diplomatic :comment "")
 (:id 82  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 83  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire sopra acuto" :root :a :ordine 1 :flag :diplomatic :comment "»primo« ist selbstverständlicherweise zu ergänzen.")
 (:id 84  :category :key      :libro 5 :chapter 8 :folio (106 . :verso) :original-name "Alamire primo" :root :a :ordine 1 :flag :diplomatic :comment "")
 (:id 85  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :a :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "Diese Note kommt 20x hintereinander vor.")
 (:id 86  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :f :chromatic-alteration :sharp :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 87  :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza minore]" :departure 85 :destination 86 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 88  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :f :chromatic-alteration nil :enharmonic-alteration :dot :flag :diplomatic :comment "")
 (:id 89  :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza minore propinqua]" :departure 85 :destination 88 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 90  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :f :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 91  :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza maggiore]" :departure 85 :destination 90 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 92  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :e :chromatic-alteration :sharp :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 93  :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza maggiore propinqua]" :departure 85 :destination 92 :direction :down :group :terza :flag :diplomatic :comment "")
 (:id 94  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :d :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 95  :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[quinta]" :departure 85 :destination 94 :direction :down :group :quinta :flag :diplomatic :comment "")
 (:id 96  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :c :chromatic-alteration :sharp :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 97  :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta minore]" :departure 85 :destination 96 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 98  :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :c :chromatic-alteration nil :enharmonic-alteration :dot :flag :diplomatic :comment "")
 (:id 99  :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta minore propinqua]" :departure 85 :destination 98 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 100 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :c :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 101 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta maggiore]" :departure 85 :destination 100 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 102 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :b :chromatic-alteration :sharp :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 103 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta maggiore propinqua]" :departure 85 :destination 102 :direction :down :group :sesta :flag :diplomatic :comment "")
 (:id 104 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :a :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 105 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[ottava]" :departure 85 :destination 104 :direction :down :group :ottava :flag :diplomatic :comment "")
 (:id 106 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :c :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 107 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza minore]" :departure 85 :destination 106 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 108 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :c :chromatic-alteration nil :enharmonic-alteration :dot :flag :diplomatic :comment "")
 (:id 109 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza minore propinqua]" :departure 85 :destination 108 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 110 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :c :chromatic-alteration :sharp :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 111 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza maggiore]" :departure 85 :destination 110 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 112 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :d :chromatic-alteration :flat :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 113 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[terza maggiore propinqua]" :departure 85 :destination 112 :direction :up :group :terza :flag :diplomatic :comment "")
 (:id 114 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :e :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 115 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[quinta]" :departure 85 :destination 114 :direction :up :group :quinta :flag :diplomatic :comment "")
 (:id 116 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :f :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 117 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta minore]" :departure 85 :destination 116 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 118 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :f :chromatic-alteration nil :enharmonic-alteration :dot :flag :diplomatic :comment "")
 (:id 119 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta minore propinqua]" :departure 85 :destination 118 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 120 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :f :chromatic-alteration :sharp :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 121 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta maggiore]" :departure 85 :destination 120 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 122 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :g :chromatic-alteration :flat :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 123 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[sesta maggiore propinqua]" :departure 85 :destination 122 :direction :up :group :sesta :flag :diplomatic :comment "")
 (:id 124 :category :note     :libro 5 :chapter 8 :folio (107 . :recto) :root :a :chromatic-alteration nil :enharmonic-alteration nil :flag :diplomatic :comment "")
 (:id 125 :category :interval :libro 5 :chapter 8 :folio (107 . :recto) :original-name "[ottava]" :departure 85 :destination 124 :direction :up :group :ottava :flag :diplomatic :comment "")
 )
