* Flags
- :DIPLOMATIC :: Quellentreuer Zustand
- :REGULAR-SHORTHAND :: Als Ergänzung zu :DIPLOMATIC, wenn eine
  eindeutige und häufig auftretende Verkürzung des Notennamens auftritt.
- :OBVIOUS-CORRECTION :: Klarer Fehler, nie in Kombination mit :DIPLOMATIC.
- :RECOMMENDED-CORRECTION :: Diskutabler Eingriff, der einer
  kuratierten Lesart entspricht. Diese Fälle müssten stets explizit
  begründet werden (siehe COMMENT-Element).
- :OMITTED-TEXT :: Vorschlag zur Ergänzung eines vom Drucker
  irrtümlich ausgelassenen Textfragments. Nie in Kombination mit :DIPLOMATIC.
- :EXTENDED-KEY :: Enthält eine Taste, die nicht den üblichen 36
  Tasten des Archicembalo entsprechen, kann gleichzeitig mit
  :DIPLOMATIC auftreten.
- :QUINTENSCHAUKEL :: Nur für Intervalle sinnvoll. Das Intervall ist
  nur gültig, wenn es in der Quintenschaukel-Stimmung auftritt.
- :PROPINQUA :: Intervall, das um eine /diesis/ vergrössert ist.
- :PROPINQUISSIMA :: Intervall, das um ein /comma/ vergrössert ist.
- :INVERSE-PROPINQUA :: Intervall, das um eine /diesis/ verkleinert
  ist. In Kombination mit :DIPLOMATIC.
- :AVOID-INVERSE-PROPINQUA :: Korrektur zur Vermeidung der :INVERSE-PROPINQUA.
- :INVERSE-PROPINQUISSIMA :: Intervall, das um ein /comma/
  verkleinert ist. In Kombination mit :DIPLOMATIC.
- :AVOID-INVERSE-PROPINQUISSIMA :: Korrektur zur Vermeidung der :INVERSE-PROPINQUISSIMA.
- :EXOTIC :: Generell bemerkenswerte Stelle, die in irgendeiner Form
  unregelmässig scheint. In Kombination mit :DIPLOMATIC.
- :AVOID-EXOTIC :: Korrektur
- :PROPINQUA-PROPINQUISSIMA :: Intervall, das um eine /diesis/ und
  ein /comma/ vergrössert ist. Kann auch in Kombination mit
  :INVERSE-PROPINQUA auftreten. Üblicherweise in Kombination mit :DIPLOMATIC.
- :SEPTIMAL :: Kennzeichnet ein septimales Intervall, also eine um
  eine /diesis/ verkleinerte /terza minore/ (7:6, »septimale
  Mollterz«) und die um eine /diesis/ verkleinerte kleine Septime
  bzw. übermässige Sexte (7:4, »Naturseptime«).

* interval-group-identity
- :DIESIS, schliesst auch /comma/ mit ein
- :SEMITONO
- :TERZA
- :QUINTA
- :SESTA
- :OTTAVA

* Intervallgrössen
Die Intervallnamen-Attribute /propinqua/ und /propinquissima/ stehen
für eine Grauzone, die das Bild einer exakt definierbaren
Intervallgrösse aufrauht. Es geht darum, dass Abweichungen von einem
abstrakt definierbaren Intervall als vollwertige Repräsentationen von
Intervallen akzeptiert werden. Dabei werden zwei Grössenordnungen von
Abweichungen verwendet. /propinqua/ steht für eine signifikante
Abweichung von rund einer /diesis. Damit liegt eine solche Abweichung
im Bereich der kontrapunktisch relevanten Intervallen, die als
Stimmführungen vorkommen können. /propinquissima/ steht für eine
deutlich kleinere Abweichung, die als /comma/ beschrieben wird
höchstens die Hälfte einer /propinqua/ umfassen können. Damit liegen
sie im Bereich feiner Intonationsvarianten von Intervallen, die
kontrapunktisch betrachtet gleichbedeutend sind.

Am Beispiel der Terz kann dies veranschaulicht werden. Eine /terza
minore propinqua/ liegt genau zwischen einer /terza minore/ und einer
/terza maggiore/ und wird von Vicentino auch /terza più di minore/
genannt. /terza minore propinqua/ und /terza più di minore/ sind also
gleichbedeutend. Über einem liegenden D führt die Melodie F - Ḟ - F♯
durch die drei Terzen /terza minore/, /terza propinqua/ und /terza
maggiore/. Strebt man einen konsonanten Kontrapuntk an, könnte eine
zweite Stimme beispielsweise D - Ḃ♭ - A lauten. Wird an Stelle der
/terza minore propinqua/ eine /terza minore propinquissima/ verwendet,
würde die Meldie über dem liegenden D F -- Fʼ -- F♯ lauten. Damit wird
abhängig von der verwendeten Stimmung zwischen verschieden
temperierten /terze minori/ gewechselt, um dann mit /semitono minore/
von Fʼ zu F♯ zu schreiten. F -- Fʼ ist kontrapunktisch nicht relevant,
spielt aber in der klanglichen Realisierung eine wesentliche Rolle.

Die Frage, ob /propinqua/ und /propinquissima/ Intervalle stets
vergrössern, oder auch verkleinern können kann für /L'antica musica/
nicht mit Gewissheit beantwortet werden. Die Analyse aller Tonhöhen in
der Kapitelstrecke von b5-c8 bis b5-c38 lässt zwei Schlussfolgerungen
zu. In beiden kann die /propinquissima/ in beide Richtungen wirken. In
der ersten Schlussfolgerung ist dies auch für die /propinqua/ der
Fall, in der zweiten wird die /propinqua/ jedoch ausschliesslich als
intervallvergrössernd betrachtet.

Betrachtet man die Intervalle in den erwähnten Kapiteln vor dem
Hintergrund der ersten Schlussfolgerung ergeben sich folgende
zu unterscheidende Situationen. Dabei ist die spezifische Grösse von
/diesis/ und /comma/ nicht relevant, es geht um eine qualitative
Betrachtung der erwähnten Intervallmodifikationen.

- /propinqua/ :: Um eine /diesis/ vergrössert.
- inverse /propinquissima/ einer /propinqua/ :: Um eine /diesis/
  vergrössert und um ein /comma/ verkleinert.
- /propinquissima/ :: Um ein /comma/ vergrössert.
- Unverändertes Intervall.
- inverse /propinquissima/ :: Um ein /comma/ verkleinert.
- /propinquissima/ einer inverse /propinqua/ :: Um eine /diesis/
  verkleinert und um ein /comma/ vergrössert.
- inverse /propinqua/ :: Um eine /diesis verkleinert/.

Wenn die Stimmung so konstruiert ist, dass ein /comma/ genau die
Hälfte einer /diesis/ ausmacht, vereinfacht sich diese Auflistung,
weil dann eine /propinqua/ eine doppelte /propinquissima/ ausmacht.

- /propinqua/ :: Um eine /diesis/ vergrössert
- /propinquissima/ :: Um ein /comma/ vergrössert, bzw. um eine
  /propinquissima/ vergrössert und um ein /comma/ verkleinert.
- Unverändertes Intervall
- inverse /propinquissima/ :: Um ein /comma/ verkleinert, bzw. um eine
  /diesis/ verkleinert und um ein /comma/ vergrössert.
- inverse /propinqua/ :: Um eine /propinqua/ verkleinert.

Die klangliche Realität dieser modifizierten Intervalle im
Archicembalo hängt vom Stimmungssystem ab. Im Folgenden werden zwei
Szenarien exemplarisch betrachtet, um die Verschränkung zwischen
Stimmungssystem und Gebrauch von /propinqua/ und /propinquissima/ zu
verdeutlichen.

Erstes Beispiel: Das Stimmungssystem des Archicembalo soll auf der
Basis der 1/4-Komma-Mitteltönigkeit konstruiert werden. In einer
solchen Stimmung besteht die /propinqua/-Modifikation aus einer reinen
/diesis/ (128:125) oder einer um rund 1/4 syntonisches Komma
verkleinerten temperierten /diesis/. Die /propinquissima/-Modifikation
beträgt stets genau 1/4 syntonisches Komma. Eine
/propinquissima/-Modifikation ist also rund ein Achtel einer
/propinqua/-Modifikation. Dieser markante Unterschied führt zu einer
eindeutigen klanglichen Unterscheidung der Intervalle, die um eine
/diesis/ vergrössert oder verkleinert sind von den Intervallen, die um
ein /comma/ vergrössert oder verkleinert sind, also die
konventionellen /propinqua/- und
/propinquissima/-Intervalle. Vicentino benennt jedoch auch die
Intervalle, die um eine /diesis/ vergrössert und um ein /comma/
verkleinert sind, und jene, die um eine /diesis/ verkleinert und ein
/comma/ vergrössert sind /propinquissima/. Im erwähnten
Fall der 1/4-Komma-Mitteltönigkeit führt dies dazu, dass ein solches
/propinquissima/-Intervall klanglich sehr nahe an einem
/propinqua/-Intervall liegt. Es befindet sich in der Grössenordnung
der /propinqua/-Modifikationen und lässt sich klanglich nicht von der
erwähnten temperierten /diesis/ in dieser Stimmung
unterscheiden. In diesem Kontext wäre deshalb die Bezeichnung
/propinqua/ für solche kombinierten /propinqua/- und
/propinquissima/-Modifikationen naheliegender.

Zweites Beispiel: Das Stimmungssystem wird auf der Basis von 1/3-Komma
angelegt und ermöglicht die /Quintenschaukel/. In diesem System gibt
es zwei sehr stark unterschiedliche /diesis/-Intervalle, und ein
/comma/, das rund 2/3 eines syntonischen Kommas ausmacht.

[xxx muss weiter ausgeführt werden, auf Basis berechneter Intervallgrössen]



[xxx Belege für Vicentinos sprachliche Beschreibungen. Vergleich mit
verwendeten Intervallen]


* Special cases
- note-name :C-ʼ (sound lower than :C by a /comma/)

* Proofreading
- [X] search for X
- [X] search for ->
- [X] search for .,
- [X] search for :obvious-correction and check for critical comment.
- [X] Condense all tags and check against list
- [X] Condense all :interval-group-identity
- [X] Condense all notenames / root/ordine mappings
  - (:A :A 1)
  - (:Aʼ :A 6)
  - (:Ȧ :A 4)
  - (:A♭ :A 3)
  - (:Ȧ♭ :A 5)
  - (:G♯ :A 2)
  - (:C♭ :B 4)
  - (:B♭ʼ :B 6)
  - (:B♮ʼ :B 6)
  - (:B♭ :B 2)
  - (:A♯ :B 3)
  - (:B♮ :B 1)
  - (:Ḃ♮ :B 4)
  - (:Ḃ♭ :B 5)
  - (:C-ʼ :C 3)
  - (:Cʼ :C 6)
  - (:C :C 1)
  - (:B♯ :C 3)
  - (:Ċ :C 4)
  - (:C♯ :D 2)
  - (:D♭ :D 3)
  - (:Ḋ♭ :D 5)
  - (:D :D 1)
  - (:Dʼ :D 6)
  - (:Ḋ :D 4)
  - (:E :E 1)
  - (:Ė :E 4)
  - (:Eʼ :E 6)
  - (:E♭ :E 2)
  - (:Ė♭ :E 5)
  - (:D♯ :E 3)
  - (:Fʼ :F 6)
  - (:F :F 1)
  - (:E♯ :F 3)
  - (:Ḟ :F 4)
  - (:F♯ :G 2)
  - (:G♭ :G 3)
  - (:Ġ♭ :G 5)
  - (:G :G 1)
  - (:Gʼ :G 6)
  - (:Ġ :G 4)

* TODOs
- [X] Add chapter index
- [ ] Resolve all :inverse-propinqua cases
- [ ] isolate all :regular-shorthand cases, compare count to spelled out cases
